name: CD - DEV (Minimal Proof)

on:
  push:
    branches: [develop]

jobs:
  prove-terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3

      - name: PROOF: Terraform Init
        working-directory: infra/terraform
        run: terraform init

      - name: PROOF: Terraform Plan (no vars)
        working-directory: infra/terraform
        run: terraform plan
