name: CD - Deploy DEV

on:
  workflow_run:
    workflows: ["CI - Build & Push Image"]
    types:
      - completed

jobs:
  deploy-dev:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: infra/terraform
        run: terraform init

      - name: Select DEV workspace
        working-directory: infra/terraform
        run: |
          terraform workspace select dev || terraform workspace new dev

      - name: Terraform Apply (DEV)
        working-directory: infra/terraform
        run: terraform apply -auto-approve -var-file=dev.tfvars
