name: CD - DEV

on:
  push:
    branches:
      - develop

jobs:
  deploy-dev:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        working-directory: infra/terraform
        run: terraform init

      - name: Select DEV workspace
        working-directory: infra/terraform
        run: |
          terraform workspace select dev || terraform workspace new dev

      - name: Terraform Apply (DEV)
        working-directory: infra/terraform
        run: terraform apply -auto-approve -var-file=dev.tfvars
